# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        cookie_domain: '.willbrooks.fr'
        cookie_path: /
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file