version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: symfony_api
    restart: unless-stopped

    working_dir: /var/www/html/api

    ports:
      - "9000:9000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      APP_ENV: prod
      APP_DEBUG: '0'

      # REQUIRED (your crash source)
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      DEFAULT_URI: ${DEFAULT_URI}

      DATABASE_URL: ${DATABASE_URL}

    # IMPORTANT: no bind mount in production