version: '3.3'

services:
  api:
    build:
      context: .
    container_name: symfony_api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/var/cache
      - /var/www/html/var/log
      - /var/www/html/vendor
      - /var/www/html/public
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
    command: php-fpm
