version: '3.3'

services:
  api:
    build:
      context: .
    container_name: symfony_api
    restart: unless-stopped
    working_dir: /var/www/html/api
    volumes:
      - .:/var/www/html/api
      - /var/www/html/api/var/cache
      - /var/www/html/api/var/log
    ports:
      - "9000:9000"
    environment:
      APP_ENV: prod
      APP_DEBUG: '0'
    command: php-fpm
